### ISSUE TITLE
Centralise BHoM assemblies folder into %AppData%\BHoM

### ISSUE THREAD

**Issue by epignatelli** [BHoM/Dynamo_Toolkit#135]

**Comment by awakeman** [comment]
@ZiolkowskiJakub any thoughts on this?

**Comment by al-fisher** [comment]
Good one to include in 3.1 nothing new clean up and improvement series of sprints perhaps.

**Comment by awakeman** [comment]
Had an idea here that since it doesn't seem possible to refer to an external library directory to instead create a library whose sole job is to bootstrap the loading of the rest of the BHoM from the central assemblies directory. I'm going to take a look at doing this this milestone. We will probably need to rename the Dynamo_Engine and Dynamo_UI dlls for 1.x and 2.x respectively as presently (as of #209) those libraries rely on being in separate directories. that or they could remain the sole libraries in the `%APPDATA%\Dynamo\Dynamo *\*\packages\BHoM\bin` folders, provided the bootstrapper loads their dependencies first.

**Comment by adecler** [comment]
Why don't you leave this to me? As discussed in the sprint kick-off meeting, I will work on Dynamo his sprint. It is unclear to me why you are suddenly jumping on this repo.

**Comment by awakeman** [comment]
Happy to leave it to you. This issue has been stagnating for some time but its importance was reignited in my mind with the changes I needed to make in the Installer on Monday as such I thought I'd take the initiative of offering up a potential solution, with implementation if necessary, to resolve it before it got made worse.

Not sure what the objection is to offering to share some of the workload involved in making general improvement of any and all toolkits especially when this particular issue resides firmly within my remit as Operations lead, regardless of who nominally "owns" the repo in question.

**Comment by adecler** [comment]
Right. Two words: coordination and focus. This is what the sprint kick-off are all about. I don't want you to be distracted and go on tangents while you already have an agreed plan for this sprint.

I suggest you take the discussion offline with @rwemay if you need further explanation.

**Comment by adecler** [comment]
Now replaced by #239
