### ISSUE TITLE
Dynamo_Toolkit: Dynamo Crashing Upon Placement of BHoM Components

### ISSUE THREAD

**Issue by kayleighhoude** [BHoM/Dynamo_Toolkit#232]
#### Description:
Working off of 20/23/4 Alpha and experiencing crash upon placement of BHoM components

#### Test file(s):

![image](https://user-images.githubusercontent.com/34316256/80243497-52471400-8635-11ea-9b6c-0bda68fde23b.png)

**Comment by michaldengusiak** [comment]
my nodes also do not work in dynamo

**Comment by adecler** [comment]
It seems that the issue here is with the wrong dlls being copied over making Dynamo unhappy. 

The simplest way to check is to put a break point here: 

![image](https://user-images.githubusercontent.com/16853390/81266957-4701d880-9078-11ea-823d-57558ed04cbe.png)

and attach to Dynamo for debugging. You then try to add a `Compute` component on the canvas.

The error is likely to be different for everyone depending on the legacy dlls left on their machines. For me, the first time I had 

```
Could not load type 'BH.oM.Reflection.Attributes.ReplacedAttribute' from assembly 'Reflection_oM, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null'.
```

Once I cleared all the Reflection_oM dlls from my buid folder and rebuilt, It fixed it. I then got another one for Reflection_Engine: 

```
Method not found: 'BH.oM.Reflection.Output`2<System.Collections.Generic.List`1<BH.oM.UI.SearchItem>,BH.oM.Data.Collections.Tree`1<!!0>> BH.Engine.UI.Compute.OrganiseItems(System.Collections.Generic.List`1<!!0>)'.
```

So I've cleaned up all my build folders and recompiled everything. For example, here's how many copied of `Reflection_oM.dll` we have (we should have only one): 

![image](https://user-images.githubusercontent.com/16853390/81271742-16716d00-907f-11ea-8c43-6e739f4e5a74.png)


Same thing for `Reflection_engine.dll`: 

![image](https://user-images.githubusercontent.com/16853390/81271803-29843d00-907f-11ea-90d8-ec613a39b62b.png)


As you can imagine, that is probably the case for a lot of other dlls.

@FraserGreenroyd will work on getting the CI checks for that running. This will hopefully fix this issue 🤞

**Comment by adecler** [comment]
@kayleighhoude , do you mind testing again now the situation is better with duplicates ?
You will have to clear your build folder before recompiling for this to work.

Personally, doing that removed a tonne of issues I had with basic use of BHoM in Dynamo.

**Comment by kayleighhoude** [comment]
@adecler no more crashing after clearing out my build folder, how can we ensure this is fixed for everyone under new installers?

![image](https://user-images.githubusercontent.com/34316256/82091433-59f25980-96c5-11ea-899b-8c64e210e7e6.png)

**Comment by FraserGreenroyd** [comment]
@kayleighhoude this will be fixed when each toolkit stops doing `copy local true` which is currently most toolkits. We did a multi-issue to get every toolkit tidied up but it'll be down to individual assignees to handle. It will be resolved by the beta release, but daily alphas might take a little longer for all the updates to trickle through.

The compliance checks will pick it up, so we need to make sure PRs undergo compliance checks as appropriate to prevent the issue from happening again.
