### ISSUE TITLE
Dynamo_Toolkit: components deserialize correctly after method output description has changed

### ISSUE THREAD

**Issue by pawelbaran** [BHoM/Dynamo_Toolkit#248]
#### Description:

After changing the output description in from _F_ to _request_, the component created before the change gets both inputs and outputs doubled, as in the screenshot (lower component is a newly created one, with correct inputs and outputs):

![image](https://user-images.githubusercontent.com/26874773/85751513-f10df080-b70a-11ea-8088-9896c76988d7.png)

Interestingly, after copy-pasting the wrongly deserialized component, the copy is fine.

**Comment by adecler** [comment]
I believe this has been fixed by the refactoring of the UI. Testing this right now, I get the expected behaviour when reopening the file: output name is changed without duplicates. 

Can you check that this is the case for you too ? Don't forget to manually clean the Roaming BHoM folder if you have ran the installer recently. Instead of waiting for the installer to be fixed (@FraserGreenroyd ) I'll do a PR to clear the BHoM folder on each post build.

**Comment by pawelbaran** [comment]
Yeah, works fine now - closing the issue.
