### ISSUE TITLE
Dynamo_Toolkit: Dynamo 2.3 and Revit crush after installing newest BHoM

### ISSUE THREAD

**Issue by arturtomczak** [BHoM/Dynamo_Toolkit#254]
#### Description:
BHoM version 3.3.0.200710
Dynamo Core version 2.3.0.5885
Revit version 20.2.20.31 20200426_1515(x64)

Dynamo canvas not working at all and displaying error as below:
![Dynamo UI error](https://user-images.githubusercontent.com/34334902/87663367-069f9480-c764-11ea-98c5-7e7de494f8d6.png)

When closing Dynamo, whole Revit crushes, with error:
![Error on closing Dynamo](https://user-images.githubusercontent.com/34334902/87663375-099a8500-c764-11ea-89e1-c1cadd07b1eb.png)

#### Steps to reproduce:
Install BHoM 3.3.0.200710 using msi installer.
Launch Revit 2020 and Dynamo.
Try to start new script or reopen existing one.

The error does not always occur on first launch after install. It happen on second/third try. 

#### Expected behaviour:
BHoM shouldn't impact the normal Dynamo behaviour.

**Comment by adecler** [comment]
I cannot reproduce the bug even after reopening multiple times. Since you are in the same office as @pawelbaran , can you check with him to see if he can work it out with you ?

I don't see how the BHoM can create the bug you are showing though. HelixToolkit is what Dynamo is using to render its 3D view (so nothing to do with one of our toolkits). If the crash happens on opening a new file, then the BHoM is not even active at this stage (it activates only once the first component is dropped on the canvas). The only interaction Dynamo can have with the BHoM is the analysis of the dll content to generate the menu. The bug is related to the camera, not the menu though.

Have you checked that the bug only happens when the BHoM is installed ?

**Comment by arturtomczak** [comment]
Thanks Arnaud

Yes, after deleting BHoM folder from AppData/.../2.3/packages the problem didn't occur. From what you say this problem should have nothing to do with it, but coincidentally it stopped crushing.

I don't know if it's helpful, but I also had another Revit (2019) open, plus Rhino with Gh (no adapters in use). After restarting the system the problem still remained, but I also had those additional programs running.

If I'm the only person with such Dynamo behaviour we can wait till August - on Monday I'm going for 2w long holiday and during my absence IT is going to format my computer due to other problems I'm having with it. If I face the same error on clean system I will let you know.

**Comment by arturtomczak** [comment]
The problem doesn't appear any more after formatting my computer.
