### ISSUE TITLE
Dynamo Revit 2.3 UI issues

### ISSUE THREAD

**Issue by pawelbaran** [BHoM/Dynamo_Toolkit#289]
#### Description:

Today I have experienced a weird issue: on creation of a code block, I could not modify it or type anything in. It looked completely inactive, as in the screenshot below. The issue disappeared after removing BHoM for Dynamo Revit 2.3. Possibly it can be related with #280?

![image](https://user-images.githubusercontent.com/26874773/105516538-4c6e8400-5cd6-11eb-8f5f-5b114a491ac8.png)

**Comment by adecler** [comment]
The problem is this:

![image](https://user-images.githubusercontent.com/16853390/105567404-9013cd00-5d6c-11eb-94fb-5b16ae8c194c.png)

If you want to read a longer rant about it: https://archi-lab.net/dll-hell-is-real/

But basically, Dynamo uses an (very) old version of AvalonEdit. Since Dynamo loads all the dlls referenced by any plugin itself into one big melting pot, we just end up with our version of AvalonEdit masking Dynamo's version. Since the two versions are different enough, the Code Block ends up not working.

I hope that all makes sense. The irony is that We don't even have the BHoM CodeEditor in Dynamo right now (and probably never will now). So what I'll do is have the CodeEditor on a separate dll in BHoM_UI and have it referenced by all UIs but Dynamo. Will get that done as soon as I have time.

**Comment by adecler** [comment]
PRs raised here:
- https://github.com/BHoM/BHoM_UI/pull/359
- https://github.com/BHoM/Grasshopper_Toolkit/pull/591
