### ISSUE TITLE
ICSharpCode.AvalonEdit.dll gets copied over to Dynamo 2.0 bin folder

### ISSUE THREAD

**Issue by pawelbaran** [BHoM/Dynamo_Toolkit#291]
#### Description:

As in the title: the file causing the weird behaviour reported in #289 is still present in _%AppData%\Dynamo\Dynamo Revit\2.0\packages\BHoM\bin_ both after compilation as well as after installation from today's Alpha. My intuitive bet is that it is a Dynamo_Toolkit issue, but please feel free to transfer to the installer if needed.

Dynamo 2.3 works fine thanks to different assembly loading mechanism.

**Comment by adecler** [comment]
Well, the problem is that 2.0 is still copying all the dlls from ProgramData to its bin folder (2.3 just copies the minimum required and then provides a link to the ProgramData folder).

So the best action here (that I could think of) is to explicitly delete the AvalonEdit dll from the bin folder in post build of 2.0.
